development:
  adapter: postgresql
  encoding: unicode
  database: myflix_development
  pool: 5
  username: jasonli
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: myflix_test
  pool: 5
  username: jasonli
  password:
  
production:
  adapter: postgresql
  encoding: unicode
  database: myflix-production
  pool: 5
  host: localhost
  username: jasonli
  password: